# Generated by Django 4.2.23 on 2025-06-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("mobile_number", "is_primary"),
                name="unique_primary_patient_per_mobile",
            ),
        ),
    ]
