# Generated by Django 4.2.23 on 2025-06-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[
                            ("ONLINE_DEFAULT", "Online Default"),
                            ("PROMOTIONAL", "Promotional"),
                            ("BULK_BOOKING", "Bulk Booking"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "max_uses",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of times this coupon can be used in total. Null means unlimited.",
                        null=True,
                    ),
                ),
                ("current_uses", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "coupons",
                "ordering": ["-created_at"],
            },
        ),
    ]
