# Generated by Django 4.2.23 on 2025-06-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingMember",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_primary_contact", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookingOrder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "online_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "promotional_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("final_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_assisted_booking", models.BooleanField(default=False)),
                ("number_of_members", models.IntegerField(default=1)),
                (
                    "resource_hold_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp for when slots were held",
                        null=True,
                    ),
                ),
                (
                    "his_invoice_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("his_invoice_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookingSlot",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("total_slots", models.IntegerField(default=20)),
                ("available_slots", models.IntegerField()),
                ("is_holiday", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="packages.package",
                    ),
                ),
            ],
        ),
    ]
