# Generated by Django 4.2.23 on 2025-06-16 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('packages', '0001_initial'),
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingorder',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='assisted_by',
            field=models.ManyToManyField(blank=True, to='users.staffmember'),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='booking_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.bookingslot'),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='coupon_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.coupon'),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.package'),
        ),
        migrations.AddField(
            model_name='bookingmember',
            name='booking_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='bookings.bookingorder'),
        ),
        migrations.AddField(
            model_name='bookingmember',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingslot',
            unique_together={('date', 'time', 'package')},
        ),
    ]
