# Generated by Django 4.2.23 on 2025-06-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_patient_is_primary_and_more"),
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookingmember",
            unique_together={("booking_order", "patient")},
        ),
    ]
