# Generated by Django 4.2.23 on 2025-06-19 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingorder",
            name="payment_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_orders",
                to="payments.paymenttransaction",
            ),
        ),
    ]
